### ISSUE TITLE
请问这是NiuParser的第几个版本？

### ISSUE THREAD

**Issue by sefira** [banyh/pyNiuParser#1]
NiuParser从1.0.0到1.3.0一共有四个版本，请问您转换的这是哪一个版本呢？

**Comment by banyh** [comment]
確切的版本忘記了，但是在2016九月作的，所以應該是1.3.0。

**Comment by sefira** [comment]
@fallcat 后来没用哈，还是用的NiuParser~

**Comment by fallcat** [comment]
@sefira 方便的话可以发我一份NiuParser么？官网上的挂了到处都找不到。rachel_you@outlook.com。万分感谢！
